name: testing

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python test.py
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: make pdf
        env:
          TEXINPUTS: ".:pdf/kactl-include/:"
          max_print_line: 1048576
        uses: dante-ev/latex-action@latest
        with:
          root_file: code/main.tex
          compiler: pdflatex
          args: -shell-escape -output-directory pdf/build/

